### ISSUE TITLE
Text cannot be copied in firefox

### ISSUE THREAD

**Issue by kamaradclimber** [clems4ever/mesos-term#21]
Text displayed in mesos-term can be copied in chrome (and chromium) but not in firefox.

Firefox 67.0 64-bits on linux.

**Comment by clems4ever** [comment]
This will be solved with https://github.com/clems4ever/mesos-term/pull/28

**Comment by clems4ever** [comment]
The fix has been released, the issue should now be solved. Please reopen the issue if I missed something.
